# Generated by Django 5.1.15 on 2026-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('commission_rate', models.FloatField(default=0.1, help_text='e.g. 0.10 = 10%')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
