# Generated by Django 5.1.15 on 2026-09-12 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_pin_hash', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('mariage', 'Mariage'), ('sport', 'Sport'), ('bapteme', 'Baptême'), ('anniversaire', 'Anniversaire'), ('evenement_religieux', 'Événement religieux'), ('concert', 'Concert'), ('remise_diplome', 'Remise de diplôme'), ('ecole', 'École'), ('entreprise', 'Entreprise'), ('mode', 'Mode'), ('shooting_individuel', 'Shooting individuel'), ('evenement_public', 'Événement public'), ('artistique', 'Artistique'), ('autre', 'Autre')], max_length=40)),
                ('cover_photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('ARCHIVÉ', 'Archivé'), ('SUSPENDU', 'Suspendu')], default='BROUILLON', max_length=20)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('CODE_PIN', 'Protégé par code'), ('PRIVE', 'Privé (invitation uniquement)')], default='PUBLIC', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('photos_count', models.PositiveIntegerField(default=0)),
                ('default_price_per_photo_cfa', models.PositiveIntegerField(default=2000)),
                ('pack_price_cfa', models.PositiveIntegerField(blank=True, null=True)),
                ('full_gallery_price_cfa', models.PositiveIntegerField(blank=True, null=True)),
                ('watermark_enabled', models.BooleanField(default=True)),
                ('watermark_text', models.CharField(blank=True, max_length=255)),
                ('watermark_position', models.CharField(choices=[('center', 'Centre'), ('bottom-right', 'Bas droite'), ('bottom-left', 'Bas gauche'), ('top-right', 'Haut droite'), ('tile', 'Mosaïque')], default='center', max_length=20)),
                ('watermark_opacity', models.FloatField(default=0.45)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='photographers.photographerprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClientGalleryAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(max_length=254)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'client gallery accesses',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_pin_hash', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('CODE_PIN', 'Protégé par code'), ('PRIVE', 'Privé (invitation uniquement)')], default='PUBLIC', max_length=20)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['photographer', 'status'], name='events_even_photogr_6104be_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientgalleryaccess',
            unique_together={('event', 'client_email')},
        ),
    ]
