# Generated by Django 5.1.15 on 2026-09-13 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('photos', '0002_alter_photo_original_alter_photo_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover_photo_url',
        ),
        migrations.AddField(
            model_name='event',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo'),
        ),
    ]
