# Generated by Django 5.1.15 on 2026-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_cover_photo_url_event_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='watermark_position',
            field=models.CharField(choices=[('center', 'Centre'), ('bottom-right', 'Bas droite'), ('bottom-left', 'Bas gauche'), ('top-right', 'Haut droite'), ('tile', 'Mosaïque')], default='tile', max_length=20),
        ),
    ]
