# Generated by Django 5.1.15 on 2026-09-12 10:00

import apps.orders.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('raw_webhook_payload', models.JSONField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, max_length=30, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('total_amount_cfa', models.PositiveIntegerField()),
                ('platform_commission_cfa', models.PositiveIntegerField(default=0)),
                ('photographer_earnings_cfa', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('CARTE_BANCAIRE', 'Carte bancaire')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Payée'), ('FAILED', 'Échouée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=20)),
                ('access_granted_until', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='photographers.photographerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('SINGLE', 'Photo unique'), ('PACK', 'Pack'), ('FULL_GALLERY', 'Galerie complète')], default='SINGLE', max_length=20)),
                ('title_snapshot', models.CharField(max_length=255)),
                ('price_cfa', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
