# Generated by Django 5.1.15 on 2026-09-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['photographer', 'payment_status'], name='orders_orde_photogr_8828ab_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_email'], name='orders_orde_client__530bb5_idx'),
        ),
    ]
