# Generated by Django 5.1.15 on 2026-09-12 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('STUDIO', 'Studio')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_cfa_per_month', models.PositiveIntegerField(default=0)),
                ('storage_limit_mb', models.PositiveBigIntegerField()),
                ('max_active_events', models.PositiveIntegerField(blank=True, help_text='null = illimité', null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('CANCELED', 'Annulé'), ('PAST_DUE', 'Paiement en retard')], default='ACTIVE', max_length=20)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='photographers.photographerprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
