# Generated by Django 5.1.15 on 2026-09-12 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('PHOTO', 'Photo'), ('EVENT', 'Événement'), ('PHOTOGRAPHER', 'Photographe')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(choices=[('CONTENU_INAPPROPRIE', 'Contenu inapproprié'), ('DROITS_AUTEUR', "Atteinte aux droits d'auteur"), ('SPAM', 'Spam / arnaque'), ('AUTRE', 'Autre')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', "En cours d'examen"), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='OUVERT', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx'), models.Index(fields=['status'], name='moderation__status_3fc7e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('SUPPRESSION_PHOTO', 'Suppression de photo'), ('SUSPENSION_EVENEMENT', "Suspension d'événement"), ('SUSPENSION_PHOTOGRAPHE', 'Suspension de photographe'), ('AVERTISSEMENT', 'Avertissement'), ('REJET_SIGNALEMENT', 'Signalement rejeté sans action')], max_length=30)),
                ('target_type', models.CharField(choices=[('PHOTO', 'Photo'), ('EVENT', 'Événement'), ('PHOTOGRAPHER', 'Photographe')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='moderation.report')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
