# Generated by Django 5.1.15 on 2026-09-12 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('portfolio_url', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVÉ', 'Approuvé'), ('REFUSÉ', 'Refusé'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('STUDIO', 'Studio')], default='FREE', max_length=20)),
                ('storage_used_mb', models.PositiveBigIntegerField(default=0)),
                ('storage_max_mb', models.PositiveBigIntegerField(default=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVÉ', 'Approuvé'), ('REFUSÉ', 'Refusé'), ('SUSPENDU', 'Suspendu')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='photographers.photographerprofile')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_cfa', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='photographers.photographerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('SALE_CREDIT', 'Vente créditée'), ('COMMISSION_DEBIT', 'Commission plateforme'), ('PAYOUT', 'Versement au photographe'), ('ADJUSTMENT', 'Ajustement manuel')], max_length=30)),
                ('amount_cfa', models.BigIntegerField(help_text='Positive=credit, negative=debit')),
                ('balance_after_cfa', models.BigIntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. related order number', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='photographers.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='photographerprofile',
            index=models.Index(fields=['status'], name='photographe_status_aba1d9_idx'),
        ),
    ]
