# Generated by Django 5.1.15 on 2026-09-12 10:00

import apps.photos.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('original', models.FileField(upload_to=apps.photos.models.original_upload_path)),
                ('preview', models.ImageField(blank=True, upload_to=apps.photos.models.preview_upload_path)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.photos.models.thumbnail_upload_path)),
                ('watermarked', models.ImageField(blank=True, upload_to=apps.photos.models.watermarked_upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('price_cfa', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('photo_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PROCESSING', 'En traitement'), ('READY', 'Prête'), ('FAILED', 'Échec du traitement'), ('QUARANTINED', 'En quarantaine')], default='PROCESSING', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.gallery')),
            ],
            options={
                'ordering': ['photo_number'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_accesses', to='orders.orderitem')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='photos.photo')),
            ],
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'gallery'], name='photos_phot_event_i_08cf91_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', 'photo_number'], name='photos_phot_event_i_6fc3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='photoaccess',
            index=models.Index(fields=['photo', 'client_email'], name='photos_phot_photo_i_5aa1bf_idx'),
        ),
    ]
