# Generated by Django 5.1.15 on 2026-09-12 10:07

import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.FileField(max_length=300, upload_to=apps.photos.models.original_upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='preview',
            field=models.ImageField(blank=True, max_length=300, upload_to=apps.photos.models.preview_upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=300, upload_to=apps.photos.models.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='watermarked',
            field=models.ImageField(blank=True, max_length=300, upload_to=apps.photos.models.watermarked_upload_path),
        ),
    ]
